### PR TITLE
EZTVApp: Implement simple search and display in EZTVAdapter

### PR DESCRIPTION
**Pull request by regalstreak**
Why not?

### CODE REVIEW

**Comment by akhilnarang** [comment]
Rebase over the latest please :)

**Comment by out386** [comment]
Da fork 😂
Now poor Neil has to rewrite that in KT.

**Comment by msfjarvis** [comment]
Reimplemented properly in #9

**Comment by akhilnarang** [comment]
RIP

**Comment by regalstreak** [comment]
F

**Comment by out386** [comment]
Poor you. Burn Akhil with fire.

**Comment by regalstreak** [comment]
🔥🔥🔥

**Pull request closed without merging**
